### ISSUE TITLE
Critical GLib warning in test sources support

### ISSUE THREAD

**Issue by philn** [EricssonResearch/openwebrtc#139]
```
G_DEBUG=fatal_criticals OWR_USE_TEST_SOURCES=1 gdb -args ./tests/.libs/list-devices

(list-devices:19228): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

Program received signal SIGTRAP, Trace/breakpoint trap.
g_logv (log_domain=0x7ffff6fc61c4 "GLib-GObject", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fffffffd1c8) at gmessages.c:1046
1046              g_private_set (&g_log_depth, GUINT_TO_POINTER (depth));
(gdb) bt
#0  g_logv (log_domain=0x7ffff6fc61c4 "GLib-GObject", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fffffffd1c8) at gmessages.c:1046
#1  0x00007ffff68a3402 in g_log (log_domain=<optimized out>, log_level=<optimized out>, format=<optimized out>) at gmessages.c:1079
#2  0x00007ffff6898d58 in g_list_foreach (list=<optimized out>, list@entry=0x785860, func=0x7ffff6fa13e0 <g_object_unref>, user_data=user_data@entry=0x0) at glist.c:993
#3  0x00007ffff6898d7b in g_list_free_full (list=0x785860, free_func=<optimized out>) at glist.c:217
#4  0x00007ffff663636b in callback_merger_on_destroy_data (context=0x60cfd0, closure=<optimized out>) at owr_utils.c:98
#5  0x00007ffff6f9c630 in closure_invoke_notifiers (notify_type=<optimized out>, closure=<optimized out>) at gclosure.c:241
#6  g_closure_unref (closure=0x77cfa0) at gclosure.c:590
#7  0x00007ffff6636302 in _owr_utils_call_closure_with_list (callback=0x77cfa0, list=0x785640) at owr_utils.c:84
#8  0x00007ffff663c000 in cb_call_closure_with_list_later (cal=0x619110) at owr_device_list.c:74
#9  0x00007ffff689c3f5 in g_main_dispatch (context=0x60cd50) at gmain.c:3064
#10 g_main_context_dispatch (context=context@entry=0x60cd50) at gmain.c:3663
#11 0x00007ffff689c758 in g_main_context_iterate (context=0x60cd50, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3734
#12 0x00007ffff689ca1a in g_main_loop_run (loop=0x60ce90) at gmain.c:3928
#13 0x0000000000400b2f in main () at list_devices.c:71
```

**Comment by superdump** [comment]
Do you still see this issue?

**Comment by sdroege** [comment]
I don't think that was fixed. It's also something in the pulseaudio related code, so wouldn't happen elsewhere than on Linux.

**Comment by philn** [comment]
Yep it still happens, on Linux indeed. Haven't tested on other platforms.
