### ISSUE TITLE
Missing dependencies in Ubuntu Linux bootstrap

### ISSUE THREAD

**Issue by superdump** [EricssonResearch/openwebrtc#372]
We seem to be missing some dependencies in the Ubuntu Linux bootstrap. Those I have noticed so far:
* subversion
* OpenGL stuff which leads to:
```
Recipe 'gst-plugins-bad-1.0-static' failed at the build step 'post_install'
Traceback (most recent call last):
File "./cerbero/build/oven.py", line 143, in _cook_recipe
stepfunc()
File "/home/_username/cerbero/recipes/custom.py", line 93, in post_install
shutil.copyfile(src, dest)
File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/_username/cerbero/sources/linux_x86_64/gst-plugins-bad-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopengl.a'
```

**Comment by bitdivision** [comment]
@superdump Any idea what's causing the libgstgl error? Looks like libglu1-mesa-dev and libegl1-mesa-dev are being installed..

**Comment by bitdivision** [comment]
FYI for anyone who comes across this in future. My problem was an issue with PKG_CONFIG_PATH.

Cerbero does not use the correct path (for debian multiarch), I've made a bug upstream [here](https://bugzilla.gnome.org/show_bug.cgi?id=766833), but a quickfix would be the following:
```bash
#Find the location of the gl.pc file
pkg-config --debug gl
```
Then add the resulting path to the search_paths list in cerbero/cerbero/utils/\__init\__.py

The above assumes that you do actually have all the requisite mesa packages installed.
