### ISSUE TITLE
El Capitan build problem

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/openwebrtc#501]
When running `./cerbero-uninstalled -c config/osx-x86-64.cbc bootstrap` I first getting the following warning:

```
WARNING: No bootstrapper for the distro version osx_el_capitan
```
Followed by an error:
```
[(2/24) gettext -> post_install ]
[(3/24) xz -> fetch ]
-----> Fetching tarball http://tukaani.org/xz/xz-5.2.0.tar.bz2 to /Users/stefan/cerbero/sources/local/xz-5.2.0/xz-5.2.0.tar.bz2
Downloading http://tukaani.org/xz/xz-5.2.0.tar.bz2
[(3/24) xz -> extract ]
-----> Extracting tarball to /Users/stefan/cerbero/sources/build-tools/xz-5.2.0
Unpacking /Users/stefan/cerbero/sources/local/xz-5.2.0/xz-5.2.0.tar.bz2 in /Users/stefan/cerbero/sources/build-tools
Recipe 'xz' failed at the build step 'extract'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "./cerbero/build/source.py", line 112, in extract
    shell.unpack(self.download_path, self.config.sources)
  File "./cerbero/utils/shell.py", line 206, in unpack
    tf = tarfile.open(filepath, mode='r:*')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1672, in open
    raise ReadError("file could not be opened successfully")
ReadError: file could not be opened successfully
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort
```
@sdroege @nirbheek, thoughts?

**Comment by stefanalund** [comment]
Fixed in https://github.com/EricssonResearch/cerbero/pull/37
