### ISSUE TITLE
cerbero@37ee5ed83  build ios_universal error!

### ISSUE THREAD

**Issue by bamboolsu** [EricssonResearch/openwebrtc#523]
I have tried to build latest cerebra@37ee5ed83 based on the steps of https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC. 

But I always get the following build errors.
My build steps:
1, git pull --rebase;
2, 
* cd  /mnt/cerbero \
&& ./cerbero-uninstalled -c config/osx-x86-64.cbc fetch-package --full-reset --reset-rdeps openwebrtc \
&& ./cerbero-uninstalled -c config/osx-x86-64.cbc bootstrap \
&& ./cerbero-uninstalled -c config/osx-x86-64.cbc package -f openwebrtc

3, 
* cd /mnt/cerbero \
&& ./cerbero-uninstalled -c config/cross-ios-universal.cbc fetch-package --full-reset --reset-rdeps openwebrtc \
&& ./cerbero-uninstalled -c config/cross-ios-universal.cbc bootstrap \
&& ./cerbero-uninstalled -c config/cross-ios-universal.cbc package -f openwebrtc

 *  Here build  error:    $ cerbero-uninstalled -c config/cross-ios-universal.cbc package -f openwebrtc

```
[(6/31) bzip2 -> compile ]
clang  -L/Users/leo/cerbero/dist/ios_universal/lib  -arch x86_64  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -mios-simulator-version-min=6.0 -Wl,-ios_simulator_version_min,6.0 -Wl,-undefined,error -Wl,-headerpad_max_install_names -Wno-error=unused-command-line-argument -shared -Wl,-install_name -Wl,libbz2.1.0.dylib -o libbz2.1.0.6.dylib blocksort.o huffman.o crctable.o randtable.o compress.o decompress.o bzlib.o
rm -f libbz2.1.0.dylib
rm -f libbz2.dylib
ln -s libbz2.1.0.6.dylib libbz2.1.0.dylib
ln -s libbz2.1.0.6.dylib libbz2.dylib
clang -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64  -arch x86_64  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -mios-simulator-version-min=6.0 -Wall -g -Os -Wno-error=format-nonliteral -Wno-error=implicit-function-declaration   -L/Users/leo/cerbero/dist/ios_universal/lib  -arch x86_64  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -mios-simulator-version-min=6.0 -Wl,-ios_simulator_version_min,6.0 -Wl,-undefined,error -Wl,-headerpad_max_install_names -Wno-error=unused-command-line-argument -o bzip2 bzip2.o -L. -lbz2
ld: warning: ignoring file /Users/leo/cerbero/dist/ios_universal/lib/libbz2.dylib, missing required architecture x86_64 in file /Users/leo/cerbero/dist/ios_universal/lib/libbz2.dylib (4 slices)
Undefined symbols for architecture x86_64:
  "_BZ2_bzRead", referenced from:
      _uncompress in bzip2.o
      _testf in bzip2.o
  "_BZ2_bzReadClose", referenced from:
      _uncompress in bzip2.o
      _testf in bzip2.o
  "_BZ2_bzReadGetUnused", referenced from:
      _uncompress in bzip2.o
      _testf in bzip2.o
  "_BZ2_bzReadOpen", referenced from:
      _uncompress in bzip2.o
      _testf in bzip2.o
  "_BZ2_bzWrite", referenced from:
      _compress in bzip2.o
  "_BZ2_bzWriteClose64", referenced from:
      _compress in bzip2.o
  "_BZ2_bzWriteOpen", referenced from:
      _compress in bzip2.o
  "_BZ2_bzlibVersion", referenced from:
      _main in bzip2.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bzip2] Error 1
Running command 'make -f Makefile-libbz2_dylib; make EXT='

Recipe 'bzip2' failed at the build step 'compile'
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort
```

Anybody have some suggests for this build error?

**Comment by superdump** [comment]
This is possibly because x86_64 support was recently added to cross-ios-universal to allow running OpenWebRTC applications in the iPhone Simulator for 64-bit iPhones. You may need to do:

```
cd /mnt/cerbero \
&& ./cerbero-uninstalled -c config/osx-x86-64.cbc wipe --build-tools \
&& ./cerbero-uninstalled -c config/cross-ios-universal.cbc wipe --build-tools
```

And then follow the build instructions from scratch, including the mkdir and ln parts: https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC#mac-os-x-host

**Comment by bamboolsu** [comment]
Thanks for  your suggestions.  I will try it.

**Comment by bamboolsu** [comment]
@superdump Thanks for your help, this issue cannot repeat it again.

Based on you steps, I got another build error when I build cross-ios-universal. 

```
[(31/31) openwebrtc -> configure ]
Recipe 'openwebrtc' failed at the build step 'configure'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "./cerbero/build/recipe.py", line 266, in <lambda>
    setattr(cls, step, lambda self, name=step: step_func(self, name))
  File "./cerbero/build/recipe.py", line 411, in _do_step
    stepfunc()
  File "/mnt/cerbero__git_20151014/cerbero_1109/recipes/openwebrtc.recipe", line 222, in configure
    raise Exception(err_oldbuild)
Exception: Please update your openwebrtc build for the host darwin; it's out of date
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort
```

**Comment by superdump** [comment]
Note: `"Exception: Please update your openwebrtc build for the host darwin; it's out of date"``

It is possible that something was committed in openwebrtc between the time that you built for OS X and the time that you built for iOS. Try the following:

```
cd /mnt/cerbero \
&& ./cerbero-uninstalled -c config/osx-x86-64.cbc buildone openwebrtc \
&& ./cerbero-uninstalled -c config/osx-x86-64.cbc package -f openwebrtc \
&& ./cerbero-uninstalled -c config/cross-ios-universal.cbc buildone openwebrtc \
&& ./cerbero-uninstalled -c config/cross-ios-universal.cbc package -f openwebrtc
```

That should rebuild just openwebrtc for the host, fetching the code automatically. And then rebuild it for iOS. Hopefully it was just bad timing. :)

**Comment by bamboolsu** [comment]
@superdump   Thanks very much. now I can build passed.
