### ISSUE TITLE
build openwebrtc on ubuntn 14.04：Error running command: git reset

### ISSUE THREAD

**Issue by chenzij** [EricssonResearch/openwebrtc#541]
Hello team,
I used the latest version both of cerbero。step as fellow：
1、install python2.7.6
2、cd
3、git clone https://github.com/EricssonResearch/cerbero.git
4、sudo mkdir -p /opt/openwebrtc-0.3
5、sudo chown -R $UID /opt/openwebrtc-0.3
6、cd ~/cerbero \
7、./cerbero-uninstalled -c config/linux.cbc fetch-package --full-reset --reset-rdeps openwebrtc

step7 failed,the log ::
root@iZ9449so4jkZ:~/cerbero# ./cerbero-uninstalled -c config/linux.cbc fetch-package --full-reset --reset-rdeps openwebrtc
WARNING: Running as root
WARNING: Using default configuration because /root/.cerbero/cerbero.cbc is missing
Fetching the following recipes: libffi glib orc zlib bzip2 openssl gobject-introspection libjpeg-turbo libpng gstreamer-1.0 gst-plugins-base-1.0 gst-plugins-good-1.0 gst-plugins-bad-1.0 opus libvpx openh264 libsrtp libnice gstreamer-1.0-static gst-plugins-base-1.0-static gst-plugins-good-1.0-static gst-plugins-bad-1.0-static libnice-static openwebrtc openwebrtc-gst-plugins libusrsctp seed gst-python-1.0 javascriptcoregtk icu openwebrtc-gst-plugins-static
[(1/31) libffi -> Fetch ]
Running command 'git remote add origin https://github.com/NativeScript/libffi.git'
fatal: remote origin already exists.
Running command 'git remote set-url origin https://github.com/NativeScript/libffi.git'
Running command 'git fetch --all'
Fetching origin
Running command 'git reset --hard bf64a497b4b1da1aae4f14d61761f420ca48cc03'
fatal: Could not parse object 'bf64a497b4b1da1aae4f14d61761f420ca48cc03'.
Traceback (most recent call last):
  File "./cerbero/main.py", line 105, in run_command
    res = commands.run(command, self.config, self.args)
  File "./cerbero/commands/__init__.py", line 78, in run
    return _commands[command].run(config, args)
  File "./cerbero/commands/fetch.py", line 112, in run
    args.deps, args.reset_rdeps, args.full_reset)
  File "./cerbero/commands/fetch.py", line 53, in fetch
    recipe.fetch()
  File "./cerbero/build/source.py", line 175, in fetch
    git.checkout(self.repo_dir, commit)
  File "./cerbero/utils/git.py", line 163, in checkout
    env=CLEAN_ENV)
  File "./cerbero/utils/shell.py", line 157, in call
    raise FatalError(_("Error running command: %s") % cmd)
FatalError: Fatal Error: Error running command: git reset --hard bf64a497b4b1da1aae4f14d61761f420ca48cc03
***** Error running 'fetch-package' command:
Fatal Error: Error running command: git reset --hard bf64a497b4b1da1aae4f14d61761f420ca48cc03
usage: cerbero-uninstalled [-h] [-c CONFIG]
                           {add-recipe,rdeps,tag,genxcconfig,genlibfiles,check,list-packages,build,add-package,show-config,genvsprops,shell,run,cleanone,packageinfo,bundle-source,buildone,wipe,debug-packages,package,bootstrap,list,checkpackage,deps,gensdkshell,fetch-package,fetch}

how to fix it?

thanks and best regards!

**Comment by takacsv** [comment]
Edit recipes/openssl.recipe and make sure the version in line 9 is '1.0.2g'.
