### ISSUE TITLE
Error while building cerbero in Mac OSX version 10.10.5

### ISSUE THREAD

**Issue by SrujithPoondla** [EricssonResearch/openwebrtc#552]
while following this step 
[https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC#mac-os-x-host-target](url)

I am getting this error

```
Ram-MacBook-Pro:cerbero ram$ cd ~/cerbero && ./cerbero-uninstalled -c config/osx-x86-64.cbc fetch-package --full-reset --reset-rdeps openwebrtc && ./cerbero-uninstalled -c config/osx-x86-64.cbc bootstrap && ./cerbero-uninstalled -c config/osx-x86-64.cbc package -f openwebrtc
WARNING: Using default configuration because /Users/ram/.cerbero/cerbero.cbc is missing
Traceback (most recent call last):
  File "./cerbero/utils/__init__.py", line 261, in parse_file
    execfile(filename, dict)
  File "/Users/ram/cerbero/config/darwin.config", line 60, in <module>
    os.makedirs(incl_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Frameworks/OpenWebRTC.framework/Versions/0.3/include'
Configuration Error: Could not include config file (/Users/ram/cerbero/config/darwin.config)
```

**Comment by superdump** [comment]
`OSError: [Errno 13] Permission denied: '/Library/Frameworks/OpenWebRTC.framework/Versions/0.3/include`

It looks like you've missed some steps in the build instructions. Run the following:
```
sudo rm -rf ~/cerbero /Library/Frameworks/OpenWebRTC.framework
```

And then:
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC#mac-os-x-host
Followed by:
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC#mac-os-x-host-target
