### ISSUE TITLE
Build OpenWebRTC on Mac got error

### ISSUE THREAD

**Issue by wangchauyan** [EricssonResearch/openwebrtc#593]
Hi, could anyone help this ? 

```
[(15/44) openh264 -> already built ]
[(16/44) opus -> already built ]
[(17/44) libsrtp -> already built ]
[(18/44) gst-plugins-bad-1.0 -> already built ]
[(19/44) libnice -> already built ]
[(20/44) gstreamer-1.0-static -> already built ]
[(21/44) gst-plugins-base-1.0-static -> already built ]
[(22/44) gst-plugins-good-1.0-static -> already built ]
[(23/44) graphene -> already built ]
[(24/44) gst-plugins-bad-1.0-static -> fetch ]
-----> Step done
[(24/44) gst-plugins-bad-1.0-static -> extract ]
-----> Step done
[(24/44) gst-plugins-bad-1.0-static -> configure ]
-----> Step done
[(24/44) gst-plugins-bad-1.0-static -> compile ]
-----> Step done
[(24/44) gst-plugins-bad-1.0-static -> install ]
-----> Step done
[(24/44) gst-plugins-bad-1.0-static -> post_install ]
Recipe 'gst-plugins-bad-1.0-static' failed at the build step 'post_install'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "/Users/ChauyanWang/cerbero/recipes/custom.py", line 91, in post_install
    shutil.copyfile(src, dest)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/ChauyanWang/cerbero/sources/darwin_x86_64/gst-plugins-bad-1.0-static-1.7/static-build/Library/Frameworks/OpenWebRTC.framework/Versions/0.3/lib/gstreamer-1.0/libgstopus.a'
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort
```

I am trying to find any solutions from closed issues, but can't find one. 
Would anyone please help this ? 
Thanks a lot

**Comment by lucmichalski** [comment]
+1

**Comment by superdump** [comment]
This is because the GStreamer opus plugin has moved from gst-plugins-bad to gst-plugins-base.

I'm on holiday for another day so I don't have time to test but as GStreamer 1.8.0 has been released, I have merged all of the upstream cerbero changes into master and bumped the GStreamer recipes to their respective master commits. Please do a clean build and let me know how it goes. I'll be testing myself as soon as I can.

**Comment by wangchauyan** [comment]
@superdump ok, I will do clean build today, thanks a lot.

**Comment by wangchauyan** [comment]
@superdump after updating to latest code, it works well now. thanks a lot. i close this issue now.
