### ISSUE TITLE
Build Fail on Mac OS X host,  Recipe 'gtk-osx-docbook' failed at the build step 'extract'

### ISSUE THREAD

**Issue by micky-zh** [EricssonResearch/openwebrtc#631]
when I build openwebrtc on  mac os x,I got this error on build gtk-osx-docbook
  @gkiagia @philn 
./cerbero-uninstalled -c config/osx-x86-64.cbc package -f openwebrtc

/Library/Python/2.7/site-packages/distribute-0.6.10-py2.7.egg/setuptools/command/install_scripts.py:3: UserWarning: Module _hashlib was already imported from /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_hashlib.so, but /Library/Python/2.7/site-packages is being added to sys.path
  from pkg_resources import Distribution, PathMetadata, ensure_directory
    @@##/Library/Python/2.7/site-packages/distribute-0.6.10-py2.7.egg/setuptools/command/install_scripts.py:3: UserWarning: Module hashlib was already imported from /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.pyc, but /Library/Python/2.7/site-packages is being added to sys.path
  from pkg_resources import Distribution, PathMetadata, ensure_directory
WARNING: Using default configuration because /Users/baidu/.cerbero/cerbero.cbc is missing
Building the following recipes: gettext libffi zlib glib orc bzip2 openssl gobject-introspection bionic-fixup gtk-doc-lite gstreamer-1.0 opus gst-plugins-base-1.0 libvpx gst-plugins-good-1.0 openh264 libsrtp graphene gst-plugins-bad-1.0 libnice gstreamer-1.0-static gst-plugins-base-1.0-static gst-plugins-good-1.0-static gst-plugins-bad-1.0-static libnice-static libusrsctp openwebrtc-gst-plugins intltool gnome-js-common seed json-glib libxml2 gmp nettle libtasn1 gnutls glib-networking libsoup libxslt docbook-xsl docbook-xml gtk-osx-docbook itstool gtk-doc openwebrtc pygobject gst-python-1.0 openwebrtc-osx-framework openwebrtc-gst-plugins-static
[(1/49) gettext -> already built ]
[(2/49) libffi -> already built ]
[(3/49) zlib -> already built ]
[(4/49) glib -> already built ]
[(5/49) orc -> already built ]
[(6/49) bzip2 -> already built ]
[(7/49) openssl -> already built ]
[(8/49) gobject-introspection -> already built ]
[(9/49) bionic-fixup -> already built ]
[(10/49) gtk-doc-lite -> already built ]
[(11/49) gstreamer-1.0 -> already built ]
[(12/49) opus -> already built ]
[(13/49) gst-plugins-base-1.0 -> already built ]
[(14/49) libvpx -> already built ]
[(15/49) gst-plugins-good-1.0 -> already built ]
[(16/49) openh264 -> already built ]
[(17/49) libsrtp -> already built ]
[(18/49) graphene -> already built ]
[(19/49) gst-plugins-bad-1.0 -> already built ]
[(20/49) libnice -> already built ]
[(21/49) gstreamer-1.0-static -> already built ]
[(22/49) gst-plugins-base-1.0-static -> already built ]
[(23/49) gst-plugins-good-1.0-static -> already built ]
[(24/49) gst-plugins-bad-1.0-static -> already built ]
[(25/49) libnice-static -> already built ]
[(26/49) libusrsctp -> already built ]
[(27/49) openwebrtc-gst-plugins -> already built ]
[(28/49) intltool -> already built ]
[(29/49) gnome-js-common -> already built ]
[(30/49) seed -> already built ]
[(31/49) json-glib -> already built ]
[(32/49) libxml2 -> already built ]
[(33/49) gmp -> already built ]
[(34/49) nettle -> already built ]
[(35/49) libtasn1 -> already built ]
[(36/49) gnutls -> already built ]
[(37/49) glib-networking -> already built ]
[(38/49) libsoup -> already built ]
[(39/49) libxslt -> already built ]
[(40/49) docbook-xsl -> already built ]
[(41/49) docbook-xml -> already built ]
[(42/49) gtk-osx-docbook -> fetch ]
-----> Step done
[(42/49) gtk-osx-docbook -> extract ]
-----> Extracting tarball to /Users/baidu/cerbero/build/sources/darwin_x86_64/gtk-osx-docbook-1.2
Unpacking /Users/baidu/cerbero/build/sources/local/gtk-osx-docbook-1.2/gtk-osx-docbook-1.2.tar.gz in /Users/baidu/cerbero/build/sources/darwin_x86_64
Recipe 'gtk-osx-docbook' failed at the build step 'extract'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "./cerbero/build/source.py", line 120, in extract
    shell.unpack(self.download_path, self.config.sources)
  File "./cerbero/utils/shell.py", line 207, in unpack
    tf = tarfile.open(filepath, mode='r:*')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1672, in open
    raise ReadError("file could not be opened successfully")
ReadError: file could not be opened successfully
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort
4
***** Error running 'package' command:

**Comment by micky-zh** [comment]
can't download  gtk-osx-docbook-1.2.tar.gz 

I just download the file copy to the floder
