### ISSUE TITLE
cerebro-uninstalled: 404 when trying to download https://gstreamer.freedesktop.org/src/mirror/zlib-1.2.10.tar.xz

### ISSUE THREAD

**Issue by mortie** [EricssonResearch/openwebrtc#682]
I'm trying to [build for Linux](https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC), but the command `./cerbero-uninstalled -c config/linux.cbc fetch-package --full-reset --reset-rdeps openwebrtc` is failing because https://gstreamer.freedesktop.org/src/mirror/zlib-1.2.10.tar.xz doesn't exist anymore. It looks like gstreamer is now distributing tar.gz files instead of not tar.xz files, because https://gstreamer.freedesktop.org/src/mirror/zlib-1.2.10.tar.gz exists.

Additionally, http://zlib.net/zlib-1.2.10.tar.xz doesn't exist, but http://zlib.net/zlib-1.2.11.tar.xz does. Maybe consider using the file from their archive, like http://zlib.net/fossils/zlib-1.2.10.tar.gz, which won't get removed when new versions are released.

Here's the full output:

```
vor ~/job/cerbero $ ./cerbero-uninstalled -c config/linux.cbc fetch-package --full-reset --reset-rdeps openwebrtc
WARNING: Using default configuration because /home/martin/.cerbero/cerbero.cbc is missing
Fetching the following recipes: libffi glib orc zlib bzip2 openssl gobject-introspection libjpeg-turbo libpng gstreamer-1.0 gst-plugins-base-1.0 gst-plugins-good-1.0 gst-plugins-bad-1.0 opus libvpx openh264 graphene libsrtp libnice libunwind gstreamer-1.0-static gst-plugins-base-1.0-static gst-plugins-good-1.0-static gst-plugins-bad-1.0-static libnice-static openwebrtc openwebrtc-gst-plugins libusrsctp seed javascriptcoregtk icu openwebrtc-gst-plugins-static
[(1/32) libffi -> Fetch ]
fatal: remote origin already exists.
Fetching origin
HEAD is now at 60e4250 make executable
[(2/32) glib -> Fetch ]
-----> Fetching tarball http://ftp.acc.umu.se/pub/GNOME/sources/glib/2.50/glib-2.50.2.tar.xz to /home/martin/job/cerbero/build/sources/local/glib-2.50.2/glib-2.50.2.tar.xz
File /home/martin/job/cerbero/build/sources/local/glib-2.50.2/glib-2.50.2.tar.xz already downloaded.
[(3/32) orc -> Fetch ]
fatal: remote origin already exists.
Fetching origin
HEAD is now at db333e1 Back to development
[(4/32) zlib -> Fetch ]
-----> Fetching tarball http://zlib.net/zlib-1.2.10.tar.xz to /home/martin/job/cerbero/build/sources/local/zlib-1.2.10/zlib-1.2.10.tar.xz
Downloading http://zlib.net/zlib-1.2.10.tar.xz
--2017-04-28 09:55:03--  http://zlib.net/zlib-1.2.10.tar.xz
Resolving zlib.net... 69.73.132.10
Connecting to zlib.net|69.73.132.10|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-04-28 09:55:03 ERROR 404: Not Found.

Downloading https://gstreamer.freedesktop.org/src/mirror/zlib-1.2.10.tar.xz
--2017-04-28 09:55:03--  https://gstreamer.freedesktop.org/src/mirror/zlib-1.2.10.tar.xz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving gstreamer.freedesktop.org... 131.252.210.176, 2610:10:20:722:a800:ff:feda:470f
Connecting to gstreamer.freedesktop.org|131.252.210.176|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-04-28 09:55:04 ERROR 404: Not Found.

Traceback (most recent call last):
  File "./cerbero/main.py", line 105, in run_command
    res = commands.run(command, self.config, self.args)
  File "./cerbero/commands/__init__.py", line 78, in run
    return _commands[command].run(config, args)
  File "./cerbero/commands/fetch.py", line 121, in run
    args.print_only)
  File "./cerbero/commands/fetch.py", line 61, in fetch
    recipe.fetch()
  File "./cerbero/build/source.py", line 134, in fetch
    overwrite=redownload)
  File "./cerbero/utils/shell.py", line 255, in download
    raise e
FatalError
***** Error running 'fetch-package' command:

usage: cerbero-uninstalled [-h] [-c CONFIG]
                           {add-recipe,rdeps,tag,genxcconfig,genlibfiles,check,list-packages,show-config,add-package,build,genvsprops,shell,run,cleanone,packageinfo,bundle-source,buildone,wipe,debug-packages,package,bootstrap,list,checkpac
kage,deps,gensdkshell,fetch-package,fetch}
                           ...
```

**Comment by mortie** [comment]
After temporarily fixing that by changing http://zlib.net/zlib-1.2.10.tar.xz to http://zlib.net/zlib-1.2.11.tar.xz in `recipes/zlib.recipe`, the same happens with ftp://ftp.openssl.org/source/openssl-1.0.2j.tar.gz. Looking at ftp://ftp.openssl.org/source/, the closest version available is openssl-1.0.2k.tar.gz.

**Comment by tuijldert** [comment]
See https://groups.google.com/forum/#!topic/openwebrtc/lbfEtxwh4J4.

Related?

Cheers,
Tom.

**Comment by sdroege** [comment]
openwebrtc is basically unmaintained at this point. This was fixed a long time ago in upstream cerbero (as well as many other things): https://cgit.freedesktop.org/gstreamer/cerbero/commit/?id=441eed5d40672a97d0bd01e6c22b00da2b692bab
