### ISSUE TITLE
Occur error while building openwebrtc

### ISSUE THREAD

**Issue by echotor** [EricssonResearch/openwebrtc#697]
I follow the command in `https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC` and build the openwebrtc.

while I run the command ``./cerbero-uninstalled -c config/linux.cbc package -f openwebrtc``, there was an error like below:
```
WARNING: Using default configuration because /home/wangyawei/.cerbero/cerbero.cbc is missing
Building the following recipes: libffi zlib glib orc bzip2 openssl gobject-introspection libjpeg-turbo libpng gtk-doc-lite gstreamer-1.0 opus gst-plugins-base-1.0 libvpx gst-plugins-good-1.0 openh264 libsrtp graphene gst-plugins-bad-1.0 libnice libunwind gettext libusrsctp openwebrtc-gst-plugins intltool gnome-js-common icu javascriptcoregtk seed json-glib libxml2 gmp nettle libtasn1 gnutls glib-networking libsoup openwebrtc
[(1/38) libffi -> already built ]
[(2/38) zlib -> already built ]
[(3/38) glib -> already built ]
[(4/38) orc -> already built ]
[(5/38) bzip2 -> already built ]
[(6/38) openssl -> already built ]
[(7/38) gobject-introspection -> already built ]
[(8/38) libjpeg-turbo -> already built ]
[(9/38) libpng -> already built ]
[(10/38) gtk-doc-lite -> already built ]
[(11/38) gstreamer-1.0 -> already built ]
[(12/38) opus -> already built ]
[(13/38) gst-plugins-base-1.0 -> already built ]
[(14/38) libvpx -> already built ]
[(15/38) gst-plugins-good-1.0 -> already built ]
[(16/38) openh264 -> already built ]
[(17/38) libsrtp -> already built ]
[(18/38) graphene -> already built ]
[(19/38) gst-plugins-bad-1.0 -> already built ]
[(20/38) libnice -> already built ]
[(21/38) libunwind -> already built ]
[(22/38) gettext -> already built ]
[(23/38) libusrsctp -> already built ]
[(24/38) openwebrtc-gst-plugins -> already built ]
[(25/38) intltool -> already built ]
[(26/38) gnome-js-common -> already built ]
[(27/38) icu -> already built ]
[(28/38) javascriptcoregtk -> already built ]
[(29/38) seed -> already built ]
[(30/38) json-glib -> already built ]
[(31/38) libxml2 -> already built ]
[(32/38) gmp -> already built ]
[(33/38) nettle -> already built ]
[(34/38) libtasn1 -> already built ]
[(35/38) gnutls -> already built ]
[(36/38) glib-networking -> already built ]
[(37/38) libsoup -> already built ]
[(38/38) openwebrtc -> already built ]
WARNING: No specific packager available for the distro version ubuntu_xenial, using generic packager for distro debian
-----> Creating package for openwebrtc
-----> Creating debian package structure at /home/wangyawei/cerbero/build/tmplfN_3k/openwebrtc-0.3.0 for package openwebrtc
-----> Packing dependency base-system-1.0 for package openwebrtc
-----> Creating debian package structure at /home/wangyawei/cerbero/build/tmplfN_3k/openwebrtc-base-system-1.0-1.13.0.1 for package base-system-1.0
-----> Creating package for base-system-1.0
dpkg-buildpackage: source package openwebrtc-base-system-1.0
dpkg-buildpackage: source version 1.13.0.1-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by OpenWebRTC <packages@openwebrtc.org>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build openwebrtc-base-system-1.0-1.13.0.1
 fakeroot debian/rules clean
dh_testdir
dh_testroot
rm -f build-stamp
dh_clean
 debian/rules build
dh_testdir
touch build-stamp
 fakeroot debian/rules binary
dh_testdir
dh_testroot
dh_prep
dh_installdirs
dh_installdocs
dh_install
dh_testdir -a
dh_testroot -a
dh_strip -a --dbg-package=openwebrtc-base-system-1.0-dbg 
dh_link -a
dh_compress -a
dh_fixperms -a
dh_makeshlibs -a -V
dh_installdeb -a
dh_shlibdeps -a
dh_gencontrol -a
dh_md5sums -a
dh_builddeb -a
dpkg-deb: building package 'openwebrtc-base-system-1.0' in '../openwebrtc-base-system-1.0_1.13.0.1-1_amd64.deb'.
dpkg-deb: building package 'openwebrtc-base-system-1.0-dbg' in '../openwebrtc-base-system-1.0-dbg_1.13.0.1-1_amd64.deb'.
dpkg-deb: building package 'openwebrtc-base-system-1.0-dev' in '../openwebrtc-base-system-1.0-dev_1.13.0.1-1_amd64.deb'.
 dpkg-genchanges -b >../openwebrtc-base-system-1.0_1.13.0.1-1_amd64.changes
dpkg-genchanges: binary-only upload (no source code included)
 dpkg-source --after-build openwebrtc-base-system-1.0-1.13.0.1
dpkg-buildpackage: binary-only upload (no source included)
-----> Copying generated shlibs file /home/wangyawei/cerbero/build/tmplfN_3k/openwebrtc-base-system-1.0-1.13.0.1/debian/openwebrtc-base-system-1.0/DEBIAN/shlibs to /home/wangyawei/cerbero/build/tmplfN_3k/openwebrtc-base-system-1.0-shlibs
-----> Packing dependency gstreamer-1.0-core for package openwebrtc
-----> Creating debian package structure at /home/wangyawei/cerbero/build/tmplfN_3k/openwebrtc-gstreamer-1.0-core-1.13.0.1 for package gstreamer-1.0-core
WARNING: Some files required by this package are missing in the prefix:
lib/gstreamer-1.0/libgstpulse.so
-----> Creating package for gstreamer-1.0-core
WARNING: Some files required by this package are missing in the prefix:
lib/gstreamer-1.0/libgstpulse.so
-----> Copying generated shlibs file /home/wangyawei/cerbero/build/tmplfN_3k/openwebrtc-base-system-1.0-shlibs for dependency base-system-1.0 to /home/wangyawei/cerbero/build/tmplfN_3k/openwebrtc-gstreamer-1.0-core-1.13.0.1/debian/shlibs.local
dpkg-buildpackage: source package openwebrtc-gstreamer-1.0-core
dpkg-buildpackage: source version 1.13.0.1-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by OpenWebRTC <packages@openwebrtc.org>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build openwebrtc-gstreamer-1.0-core-1.13.0.1
 fakeroot debian/rules clean
dh_testdir
dh_testroot
rm -f build-stamp
dh_clean
 debian/rules build
dh_testdir
touch build-stamp
 fakeroot debian/rules binary
dh_testdir
dh_testroot
dh_prep
dh_installdirs
dh_installdocs
dh_install
dh_testdir -a
dh_testroot -a
dh_strip -a --dbg-package=openwebrtc-gstreamer-1.0-core-dbg 
dh_link -a
dh_compress -a
dh_fixperms -a
dh_makeshlibs -a -V
dh_installdeb -a
dh_shlibdeps -a
dpkg-shlibdeps: error: no dependency information found for /usr/lib/nvidia-375/libEGL.so.1 (used by debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstgl-1.0.so.0.1300.0)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/openwebrtc-gstreamer-1.0-core.substvars debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-device-monitor-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-play-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-discoverer-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-launch-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-inspect-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-typefind-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/libexec/gstreamer-1.0/gst-ptp-helper debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/libexec/gstreamer-1.0/gst-plugin-scanner debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libopenh264.so.3 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstsrtp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstudp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideoscale.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgsttypefindfunctions.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudioresample.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideoparsersbad.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstrtpmanager.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstrtp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstmulaw.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopus.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudioconvert.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstapp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstdecklink.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideocrop.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstnice.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudiotestsrc.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopenh264.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideofilter.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopengl.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvolume.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstinter.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideoconvert.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudiorate.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideorate.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstdtls.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstalaw.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideotestsrc.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstcoreelements.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvpx.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideo4linux2.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstcheck-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libopus.so.0.5.3 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstpbutils-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstrtp-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstbadbase-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libnice.so.10.6.2 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libsrtp.so.1 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstnet-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstbadallocators-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstbadvideo-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstbase-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgraphene-1.0.so.0.400.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstfft-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstapp-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstriff-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libunwind.so.8.0.1 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstcodecparsers-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libvpx.so.4.0.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstvideo-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstrtsp-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstsdp-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstgl-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstreamer-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgsttag-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstcontroller-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstaudio-1.0.so.0.1300.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstallocators-1.0.so.0.1300.0 returned exit code 2
debian/rules:31: recipe for target 'binary-arch' failed
make: *** [binary-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
Traceback (most recent call last):
  File "./cerbero/main.py", line 105, in run_command
    res = commands.run(command, self.config, self.args)
  File "./cerbero/commands/__init__.py", line 78, in run
    return _commands[command].run(config, args)
  File "./cerbero/commands/package.py", line 89, in run
    args.force, args.keep_temp)
  File "./cerbero/packages/linux.py", line 57, in pack
    self.pack_deps(output_dir, tmpdir, force)
  File "./cerbero/packages/linux.py", line 115, in pack_deps
    packager.pack(output_dir, self.devel, force, True, True, tmpdir)
  File "./cerbero/packages/linux.py", line 78, in pack
    paths = self.build(output_dir, tarname, tmpdir, packagedir, srcdir)
  File "./cerbero/packages/debian.py", line 282, in build
    shell.call('dpkg-buildpackage -rfakeroot -us -uc -D -b', srcdir)
  File "./cerbero/utils/shell.py", line 154, in call
    raise FatalError(_("Error running command: %s") % cmd)
FatalError
***** Error running 'package' command:

usage: cerbero-uninstalled [-h] [-c CONFIG]
                           {add-recipe,rdeps,tag,genxcconfig,genlibfiles,check,list-packages,show-config,add-package,build,genvsprops,shell,run,cleanone,packageinfo,bundle-source,buildone,wipe,debug-packages,package,bootstrap,list,checkpackage,deps,gensdkshell,fetch-package,fetch}
                           ...
```
Should I do to solve this problem? Anysomebody can give advices?

**Comment by echotor** [comment]
I add ``--dpkg-shlibdeps-params=--ignore-missing-info`` to configuration file and compile success.

But I don't know whether this or not?
